# See the default config file for all rules
# https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml

build:
  maxIssues: 0

naming:
  BooleanPropertyNaming:
    active: true
    allowedPattern: '^(is|has|are)'
  PackageNaming:
    active: false

formatting:
  TrailingComma:
    active: true
    allowTrailingComma: true
    allowTrailingCommaOnCallSite: true